name: chronica

include:
  - services/rss-fetcher/compose/docker-compose.yaml
  # - services/moex_fetcher/compose/docker-compose.yaml
  - services/tg-sender/compose/docker-compose.yaml
  # - services/api/compose/docker-compose.yaml
  - evidence/compose/docker-compose.yaml
  # - apps/signalfire/compose/docker-compose.yaml

networks:
  dwh-net:
    driver: bridge
    name: dwh-net
