name: chronica

services:
  chr-signalfire-dev:
    build:
      context: ../
      dockerfile: compose/Dockerfile
      target: dev
    container_name: chr-signalfire-dev
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - "33021:3000"
    volumes:
      - ../src:/app/src
      - ../index.html:/app/index.html
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../vite.config.ts:/app/vite.config.ts
      - ../tsconfig.json:/app/tsconfig.json
      - ../tsconfig.app.json:/app/tsconfig.app.json
      - ../tsconfig.node.json:/app/tsconfig.node.json
      - ../eslint.config.js:/app/eslint.config.js
      - chr-signalfire-dev-modules:/app/node_modules

  chr-signalfire-prod:
    build:
      context: ../
      dockerfile: compose/Dockerfile
      target: prod
    container_name: chr-signalfire-prod
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - "33020:80"

networks:
  dwh-net:
    external: true

volumes:
  chr-signalfire-dev-modules:
