services:
  dwh-evidence:
    build: .
    container_name: dwh-evidence
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - "33000:3000"
    env_file:
      - ../../../.env
    environment:
      - CHOKIDAR_USEPOLLING=true  # отслеживает изменения файлов
    volumes:
      - ../../evidence/build:/evidence/build
      - ../../evidence/pages:/evidence/pages
      - ../../evidence/sources:/evidence/sources
      - ../../evidence/queries:/evidence/queries
      - ../../evidence/evidence.config.yaml:/evidence/evidence.config.yaml
      - ../../evidence/package.json:/evidence/package.json
      - ../../evidence/package-lock.json:/evidence/package-lock.json
    # command: ["--init"]  # инициализация проекта при первом запуске
