input:
  generate:
    interval: "20m"
    mapping: 'root = {}'

pipeline:
  processors:
    # получение новостей без перевода.
    - label: postgres
      sql_raw:
        driver: postgres
        dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
        query: |
          WITH
            news AS (
                SELECT
                    news_id
                    , min(language_code) AS language_code
                    , min(title_txt) AS title_txt
                    , min(summary_txt) AS summary_txt
                    , count(*) AS cnt
                FROM dds.s_news_texts
                GROUP BY news_id
                HAVING count(*) = 1)
          -- новости с одним переводом
          SELECT
              n.news_id           AS news_id
              , h.news_link       AS link
              , n.language_code   AS language_code
              , n.title_txt       AS title
              , n.summary_txt     AS summary
          FROM news n
          JOIN dds.h_news h ON n.news_id = h.news_id
          UNION ALL
          -- новости без перевода
          SELECT
              news_id
              , link
              , d.language_code
              , title
              , summary
          FROM (SELECT xxh64(ods.link) AS news_id
                     , ods.link        AS link
                     , ods.feed_id     AS feed_id
                     , ods.title       AS title
                     , ods.summary     AS summary
                FROM ods.rss_news ods
                WHERE NOT EXISTS (SELECT 1
                                  FROM dds.s_news_texts s
                                  WHERE xxh64(ods.link) = s.news_id)) AS t
          LEFT JOIN dds.r_rss_feeds d ON t.feed_id = d.feed_id
          LIMIT 50

    # unarchive разбивает этот массив на отдельные сообщения
    - unarchive:
        format: json_array

    # удаление, если язык не удалось определить
    - mapping: |
        root = if this.language_code == null || this.language_code == "unknown" || this.language_code == "" { deleted() } else { this }

    # установка флагов перевода
    - mapping: |
        root = this
        root.is_ru_translation_needed = this.language_code != "ru"
        root.is_en_translation_needed = this.language_code != "en"

    # выполнение перевода на английский (если необходимо)
    - branch:
        request_map: |
          root = if this.is_en_translation_needed {
            {
              "model": "deepseek-v4-flash",
              "stream": false,
              "temperature": 0.0,
              "top_p": 0.1,
              "response_format": { "type": "json_object" },
              "messages": [
                { "role": "system", "content": "You are a highly skilled professional translator. Translate ALL text values into English. Return ONLY the translated JSON." },
                { "role": "user",   "content": {"title": this.title, "summary": this.summary}.string() }
              ]
            }
          } else { deleted() }
        processors:
          - label: http_translate_en
            http:
              url: "https://api.deepseek.com/chat/completions"
              verb: POST
              headers:
                Content-Type: "application/json"
                Authorization: "Bearer ${DEEPSEEK_API_KEY}"
              timeout: 3m
              retries: 3
              retry_period: "5s"
          - catch:
              - log:
                  level: WARN
                  message: "❌ LLM API failed after retries: ${! error() }"
          - mapping: |
              let result = this.choices.index(0).message.content.parse_json().catch(null)
              root.translated_title = if $result != null { $result.title } else { null }
              root.translated_summary = if $result != null { $result.summary } else { null }
        result_map: |
          root.translated_title_en = this.translated_title
          root.translated_summary_en = this.translated_summary

    # выполнение перевода на русский (если необходимо)
    - branch:
        request_map: |
          root = if this.is_ru_translation_needed {
            {
              "model": "deepseek-v4-flash",
              "stream": false,
              "temperature": 0.0,
              "top_p": 0.1,
              "response_format": { "type": "json_object" },
              "messages": [
                { "role": "system", "content": "You are a highly skilled professional translator. Translate ALL text values into Russian. Return ONLY the translated JSON." },
                { "role": "user",   "content": {"title": this.title, "summary": this.summary}.string() }
              ]
            }
          } else { deleted() }
        processors:
          - label: http_translate_ru
            http:
              url: "https://api.deepseek.com/chat/completions"
              verb: POST
              headers:
                Content-Type: "application/json"
                Authorization: "Bearer ${DEEPSEEK_API_KEY}"
              timeout: 3m
              retries: 3
              retry_period: "5s"
          - catch:
              - log:
                  level: WARN
                  message: "❌ LLM API failed after retries: ${! error() }"
          - mapping: |
              let result = this.choices.index(0).message.content.parse_json().catch(null)
              root.translated_title = if $result != null { $result.title } else { null }
              root.translated_summary = if $result != null { $result.summary } else { null }
        result_map: |
          root.translated_title_ru = this.translated_title
          root.translated_summary_ru = this.translated_summary

    - mapping: |
        let link = this.link.string().or("unknown")
        
        let status = if this.translated_title_en != null || this.translated_title_ru != null { 
          "✅ BACKFILL TRANSLATE SUCCESSFULLY" 
        } else { 
          "❌ BACKFILL TRANSLATE FAILED" 
        }
        
        let dir = if this.is_en_translation_needed { "ru -> en" } else { "en -> ru" }
        meta log_msg = "[%s] %s | Link: %s".format($status, $dir, $link)

    - log:
        level: INFO
        message: '${! meta("log_msg") }'

    - mapping: |
        root = []

        # оригинал
        if this.link != null && this.title != null {
          root = root.append({
            "link": this.link,
            "language_code": this.language_code,
            "title": this.title,
            "summary": this.summary,
            "model_nm": ""
          })
        }

        # перевод EN
        if this.translated_title_en != null && this.translated_summary_en != null {
          root = root.append({
            "link": this.link,
            "language_code": "en",
            "title": this.translated_title_en,
            "summary": this.translated_summary_en,
            "model_nm": "deepseek-v4-flash:cloud"
          })
        }

        # перевод RU
        if this.translated_title_ru != null && this.translated_summary_ru != null {
          root = root.append({
            "link": this.link,
            "language_code": "ru",
            "title": this.translated_title_ru,
            "summary": this.translated_summary_ru,
            "model_nm": "deepseek-v4-flash:cloud"
          })
        }

    - unarchive:
        format: json_array

    - mapping: |
        meta key = this.link.string().or("")

output:
  label: reload_news_translated
  broker:
    pattern: fan_out
    outputs:
      - label: out_postgres
        sql_raw:
          driver: postgres
          dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
          query: |
            INSERT INTO dds.s_news_texts (
              news_id, language_code, title_txt, summary_txt, model_nm
            ) VALUES (xxh64($1), $2, $3, $4, $5)
            ON CONFLICT (news_id, language_code, model_nm) DO NOTHING;
          args_mapping: |
            root = [
              this.link.string().or(""),
              this.language_code.string().or("unknown"),
              this.title.string().or(""),
              this.summary.string().or(""),
              this.model_nm
            ]
          batching:
            count: 5
            period: 1s

      - label: out_redpanda
        redpanda:
          seed_brokers: ["dwh-rp-1:9092"]
          topic: "news_translated"
          key: '${! meta("key") }'
        processors:
          - mapping: |
              root.news_link = this.link.string().or("")
              root.language_code = this.language_code.string().or("unknown")
              root.title_txt = this.title.string().or("")
              root.summary_txt = this.summary.string().or("")
          - try:
            - schema_registry_encode:
                url: "http://dwh-rp-1:8081"
                subject: "news_translated-value"
                avro_raw_json: true
          - catch:
            - log:
                level: ERROR
                message: "❌ AVRO ENCODE FAILED: ${! error() }"
            - mapping: 'root = deleted()'