input:
  generate:
    interval: "20m"
    mapping: 'root = {}'

pipeline:
  processors:
    - label: postgres
      sql_raw:
        driver: postgres
        dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
        query: |
          REFRESH MATERIALIZED VIEW CONCURRENTLY bds.b_unews;

    - log:
        level: INFO
        message: '[✅ REFRESHED] bds.b_unews'

output:
  drop: {}
