services:
  chr-evidence-dev:
    build: .
    container_name: chr-evidence-dev
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - "33001:3000"
    env_file:
      - ../../.env.server
    environment:
      - CHOKIDAR_USEPOLLING=true  # отслеживание изменения файлов
    volumes:
      - ../build:/evidence/build
      - ../static:/evidence/static
      - ../pages:/evidence/pages
      - ../sources:/evidence/sources
      - ../queries:/evidence/queries
      - ../evidence.config.yaml:/evidence/evidence.config.yaml
      - ../package.json:/evidence/package.json
      - ../package-lock.json:/evidence/package-lock.json
      - chr-evidence-dev-modules:/evidence/node_modules
    command: ["dev"]
    # command: ["init"]  # инициализация проекта при первом запуске

  chr-evidence-prod:
    build: .
    container_name: chr-evidence-prod
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - "33000:3000"
    env_file:
      - ../../.env.server
    environment:
      - EVIDENCE_REBUILD_INTERVAL=1200
      - ORIGIN=https://chronica.life
    volumes:
      - ../static:/evidence/static
      - ../pages:/evidence/pages
      - ../sources:/evidence/sources
      - ../queries:/evidence/queries
      - ../evidence.config.yaml:/evidence/evidence.config.yaml
      - ../package.json:/evidence/package.json
      - ../package-lock.json:/evidence/package-lock.json
      - chr-evidence-prod-modules:/evidence/node_modules
    command: ["prod"]

volumes:
  chr-evidence-dev-modules:
  chr-evidence-prod-modules: