input:
  redpanda:
    seed_brokers: ["dwh-rp-1:9092"]
    topics: ["dtl_s_rss_news_texts"]
    consumer_group: "LOAD_DTL_S_RSS_NEWS_EMBEDDINGS"

pipeline:
  threads: 1
  processors:
    - schema_registry_decode:
        url: "http://dwh-rp-1:8081"
    - catch:
        - log:
            level: ERROR
            message: "Error decoding avro: ${! error() }"

    # выполнение проверки, была ли новость обработана ранее
    - branch:
        processors:
          - cache:
              resource: redis_cache
              operator: get
              key: "processed:dtl.s_rss_news_embeddings:${! this.news_link }:${! this.language_code.string().or(\"unknown\") }"
        # если ключ найден, cache заменит payload, branch завершится успешно
        # если не найден, branch упадет, result_map будет пропущен
        result_map: 'meta is_processed = "true"'

    - mapping: |
        root = if meta("is_processed") == "true" { deleted() } else { this }

    # удаление, если новость не на английском языке
    - mapping: |
        root = if this.language_code != "en" { deleted() } else { this }

    # выполнение проверки, есть ли эмбеддинг новости в БД
    - branch:
        processors:
          - sql_raw:
              driver: postgres
              dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
              query: |
                SELECT 1 FROM dtl.s_rss_news_embeddings 
                WHERE news_id = xxh64($1) AND model_nm = $2
              args_mapping: |
                root = [
                  this.news_link.string().or(""),
                  "embeddinggemma:300m"
                ]
        result_map: 'meta is_processed = this.length() > 0'

    # удаление, если такая запись уже есть в БД
    - mapping: |
        root = if meta("is_processed") == true { deleted() } else { this }

    # получение эмбеддинга
    - branch:
        request_map: |
          root = {
            "model": "embeddinggemma:300m",
            "input": this.title_txt.or("") + " " + this.summary_txt.or(""),
            "dimensions": 768,
            "options": {"temperature": 0.0, "top_p": 0.1}
          }
        processors:
          - http:
              url: "http://dwh-ol-1:11434/api/embed"
              verb: POST
              headers:
                Content-Type: "application/json"
              timeout: 1m
          - mapping: |
              root.embedding = this.embeddings.0
        result_map: |
          root.embedding = this.embedding

    # логирование результата перевода
    - mapping: |
        root = if this.embedding == null { 
          throw("Failed to get embedding") 
        } else { 
          this 
        }
       
        let vec_size = this.embedding.length().string() + " dims"
        meta log_msg = "[✅ EMBEDDED] Link: %s | %s | Vct: %s | Title: %s".format(
          this.news_link.string(), this.language_code.string(), $vec_size, this.title_txt.string()
        )

    - log:
        level: INFO
        message: '${! meta("log_msg") }'

output:
  broker:
    pattern: fan_out
    outputs:
      - sql_raw:
          driver: postgres
          dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
          query: |
            INSERT INTO dtl.s_rss_news_embeddings (
              news_id, model_nm, embedding_vct
            ) VALUES (xxh64($1), $2, $3::vector)
            ON CONFLICT (news_id, model_nm) DO NOTHING;
          args_mapping: |
            root = [
              this.news_link.string().or(""),
              "embeddinggemma:300m",
              this.embedding.string()
            ]
          batching:
            count: 5
            period: 1s

      - cache:
          target: redis_cache
          key: "processed:dtl.s_rss_news_embeddings:${! this.news_link }:${! this.language_code.string().or(\"unknown\") }"
