input:
  redpanda:
    seed_brokers: ["dwh-rp-1:9092"]
    topics: ["stg_rss_news"]
    consumer_group: "LOAD_DTL_S_RSS_NEWS_TEXTS"

pipeline:
  threads: 1
  processors:
    - schema_registry_decode:
        url: "http://dwh-rp-1:8081"

    - dedupe:
        cache: redis_cache
        key: "dedupe:dtl.s_rss_news_texts:${! this.link.string() }"

    # получение из кэша language_code для this.feed_id
    - branch:
        processors:
          - try:
            - cache:
                resource: redis_cache
                operator: get
                key: "lookup:dtl.d_rss_feeds:${! this.feed_id }"
        result_map: 'root.language_code = content().string().catch("")'

    # получение из базы (при отсутствии в кэше) значения language_code для this.feed_id
    - branch:
        request_map: |
          root = if this.language_code == null || this.language_code == "" { this } else { deleted() }
        processors:
          - sql_raw:
              driver: postgres
              dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
              query: "SELECT feed_id, language_code FROM dtl.d_rss_feeds WHERE feed_id = $1"
              args_mapping: "root = [this.feed_id]"
          # добавление значения language_code в кэш
          - branch:
              request_map: |
                root = if this.length() > 0 { this } else { deleted() }
              processors:
                - cache:
                    resource: redis_cache
                    operator: set
                    key: 'lookup:dtl.d_rss_feeds:${! this.index(0).feed_id.string() }'
                    value: '${! this.index(0).language_code.string() }'

        result_map: 'root.language_code = this.index(0).language_code.catch("unknown")'

    # получение списка уже существующих переводов для этой новости из БД
    - branch:
        processors:
          - sql_raw:
              driver: postgres
              dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
              query: "SELECT language_code FROM dtl.s_rss_news_texts WHERE news_id = xxh64($1)"
              args_mapping: "root = [this.link.string()]"
        # Сохраняем массив найденных языков (например: ["en", "ru"] или [])
        result_map: |
          root.has_translations = this.map_each(item -> item.language_code).catch([])

    # установка флага необходимости перевода
    - mapping: |
        root = this
        let translations = this.has_translations.or([])
        
        # перевод на EN, если оригинал не EN, язык известен и в БД еще нет перевода 'en'
        root.is_en_translation_needed = this.language_code != "en" && this.language_code != null && !$translations.contains("en")
        
        # перевод на RU, если оригинал не RU, язык известен и в БД еще нет перевода 'ru'
        root.is_ru_translation_needed = this.language_code != "ru" && this.language_code != null && !$translations.contains("ru")

    # выполнение перевода на английский (если необходимо)
    - branch:
        request_map: |
          root = if this.is_en_translation_needed {
            {
              "model": "deepseek-v3.2:cloud",
              "stream": false,
              "options": {
                "temperature": 0.0,
                "top_p": 0.1
              },
              "system": "You are a highly skilled professional translator. Your task is to translate ALL text values in the provided JSON object into English. You MUST completely translate BOTH the 'title' and 'summary' into English. NEVER leave any text in the original language. Return ONLY the translated JSON object.",
              "prompt": {
                "title": this.title,
                "summary": this.summary
              }.string(),
              "format": {
                "type": "object",
                "properties": {
                  "title": {"type": "string"},
                  "summary": {"type": "string"}
                },
                "required": ["title", "summary"]
              }
            }
          } else { deleted() }
        processors:
          - try:
            - http:
                url: "http://dwh-ol-1:11434/api/generate"
                verb: POST
                headers:
                  Content-Type: "application/json"
                timeout: 5m
          - mapping: |
              let result = this.response.parse_json().catch(null)
              root.translated_title = if $result != null { $result.title } else { null }
              root.translated_summary = if $result != null { $result.summary } else { null }
        # объединение оригинала и результата перевода
        result_map: |
          # root - это исходный объект (со всеми полями: id, date, title, summary и т.д.)
          # this - это то, что получилось в конце цепочки processors внутри branch

          root.translated_title_en = this.translated_title
          root.translated_summary_en = this.translated_summary
          # оригинальные поля title и summary при этом не трогаются и остаются в root

    # выполнение перевода на русский (если необходимо)
    - branch:
        request_map: |
          root = if this.is_ru_translation_needed {
            {
              "model": "deepseek-v3.2:cloud",
              "stream": false,
              "options": {
                "temperature": 0.0,
                "top_p": 0.1
              },
              "system": "You are a highly skilled professional translator. Your task is to translate ALL text values in the provided JSON object into Russian. You MUST completely translate BOTH the 'title' and 'summary' into Russian. NEVER leave any text in the original language. Return ONLY the translated JSON object.",
              "prompt": {
                "title": this.title,
                "summary": this.summary
              }.string(),
              "format": {
                "type": "object",
                "properties": {
                  "title": {"type": "string"},
                  "summary": {"type": "string"}
                },
                "required": ["title", "summary"]
              }
            }
          } else { deleted() }
        processors:
          - try:
            - http:
                url: "http://dwh-ol-1:11434/api/generate"
                verb: POST
                headers:
                  Content-Type: "application/json"
                timeout: 5m
          - mapping: |
              let result = this.response.parse_json().catch(null)
              root.translated_title = if $result != null { $result.title } else { null }
              root.translated_summary = if $result != null { $result.summary } else { null }
        # объединение оригинала и результата перевода
        result_map: |
          # root - это исходный объект (со всеми полями: id, date, title, summary и т.д.)
          # this - это то, что получилось в конце цепочки processors внутри branch

          root.translated_title_ru = this.translated_title
          root.translated_summary_ru = this.translated_summary
          # оригинальные поля title и summary при этом не трогаются и остаются в root

    # логирование результата перевода
    - mapping: |
        let trans_en = this.translated_title_en != null
        let trans_ru = this.translated_title_ru != null
        let is_trans = $trans_en || $trans_ru
        let status = if $is_trans { "✅ TRANSLATED" } else { "⏩ TRANSLATE SKIPPED" }
        
        let link = this.link.string()
        let lang = this.language_code.string().or("unknown")
        let log_title = this.title.string()
        
        let targets = if $trans_en && $trans_ru { "en,ru" } 
                      else if $trans_en { "en" } 
                      else if $trans_ru { "ru" } 
                      else { "none" }
        
        let trans_preview = if $trans_en { this.translated_title_en.string() } 
                            else if $trans_ru { this.translated_title_ru.string() } 
                            else { "----" }
        
        meta log_msg = "[%s] Link: %s | %s -> %s | Title: %s | Result: %s".format(
          $status, $link, $lang, $targets, $log_title, $trans_preview
        )

    - log:
        level: INFO
        message: '${! meta("log_msg") }'

    # формирование массива [оригинал + перевод]
    - mapping: |
        root = []

        # оригинал
        if this.link != null && this.title != null && this.summary != null {
          root = root.append({
            "link": this.link,
            "language_code": this.language_code,
            "title": this.title,
            "summary": this.summary
          })
        }

        # перевод EN
        if this.translated_title_en != null && this.translated_summary_en != null {
          root = root.append({
            "link": this.link,
            "language_code": "en",
            "title": this.translated_title_en,
            "summary": this.translated_summary_en
          })
        }
        
        # перевод RU
        if this.translated_title_ru != null && this.translated_summary_ru != null {
          root = root.append({
            "link": this.link,
            "language_code": "ru",
            "title": this.translated_title_ru,
            "summary": this.translated_summary_ru
          })
        }

    # разбиение массива на отдельные сообщения
    - unarchive:
        format: json_array

    # добавление в meta поля key для использования в outputs
    - mapping: |
        meta key = this.link.string().or("")

output:
  broker:
    pattern: fan_out
    outputs:
      - sql_raw:
          driver: postgres
          dsn: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
          query: |
            INSERT INTO dtl.s_rss_news_texts (
              news_id, language_code, title_txt, summary_txt
            ) VALUES (xxh64($1), $2, $3, $4)
            ON CONFLICT (news_id, language_code) DO NOTHING;
          args_mapping: |
            root = [
              this.link.string().or(""),
              this.language_code.string().or("unknown"),
              this.title.string().or(""),
              this.summary.string().or("")
            ]
          batching:
            count: 5
            period: 1s

      - redpanda:
          seed_brokers: ["dwh-rp-1:9092"]
          topic: "dtl_s_rss_news_texts"
          key: '${! meta("key") }'
        processors:
          - mapping: |
              root.news_link = this.link.string().or("")
              root.language_code = this.language_code.string().or("unknown")
              root.title_txt = this.title.string().or("")
              root.summary_txt = this.summary.string().or("")

          - schema_registry_encode:
              url: "http://dwh-rp-1:8081"
              subject: "dtl_s_rss_news_texts-value"
              avro_raw_json: true